services:
  postgres:
    image: postgres:16
    container_name: skysports_postgres
    environment:
      POSTGRES_USER: skysports
      POSTGRES_PASSWORD: skysports
      POSTGRES_DB: skysports
    ports:
      - "5432:5432"
    volumes:
      - skysports_pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: skysports_redis
    ports:
      - "6379:6379"

volumes:
  skysports_pgdata:
